# ░██████╗░██╗░██████╗░░█████╗░░█████╗░██╗░░██╗░█████╗░████████╗
# ██╔════╝░██║██╔════╝░██╔══██╗██╔══██╗██║░░██║██╔══██╗╚══██╔══╝
# ██║░░██╗░██║██║░░██╗░███████║██║░░╚═╝███████║███████║░░░██║░░░
# ██║░░╚██╗██║██║░░╚██╗██╔══██║██║░░██╗██╔══██║██╔══██║░░░██║░░░
# ╚██████╔╝██║╚██████╔╝██║░░██║╚█████╔╝██║░░██║██║░░██║░░░██║░░░
# ░╚═════╝░╚═╝░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░
#
# /gigachat - перезагрузить плагин (Право на использование: gigachat.command.reload)
#
#
# ESSENTIALS / SUPER_VANISH / CMI
vanish-provider: ESSENTIALS

# Мне стало лень выносить в отдельный конфиг
broadcast:
  command: "broadcast"
  aliases: [ "bc", "notify" ]
  # Поддерживаемые плейсхолдеры:
  # {prefix} {player} {suffix} {message}
  format: |-
    &7[&eОБЪЯВЛЕНИЕ&7] &f{message}
    &fОт: &6{player}
  # Указывать в миллисекундах
  cooldown: 30000
  # Форматирование текста.
  # LEGACY - цвет через & и hex &#
  # LEGACY_ADVANCED - улучшенный аналог legacy с поддержкой &## формата hex
  # MINIMESSAGE - цвет через <цвет> (был добавлен в новых версиях (1.17+))
  serializer: LEGACY
  hover:
    # Включение модуля
    enable: false
    # Доступные действия: OPEN_URL, OPEN_FILE, RUN_COMMAND, SUGGEST_COMMAND, CHANGE_PAGE, COPY_TO_CLIPBOARD
    click-action: 'SUGGEST_COMMAND'
    # Команда/ссылка или другое
    click-value: '/m {player} '
    # Само сообщение которое будет показываться при наведении
    text: " &fНаписать &e{player} "

disable-own-chat:
  command: "disablechat"
  aliases: []
